name: embulan_boroq_anjani_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  pdf: ^3.12.0
  printing: ^5.14.3
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  qr_flutter: ^4.1.0 
  google_sign_in: ^6.2.1
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  assets:
    - assets/qris.png

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21